<a href="https://colab.research.google.com/github/sakshammverma/AIClinic/blob/main/Medicine_Recommendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Loading the Dataset**

In [27]:
import numpy as np
import pandas as pd
df=pd.read_csv("Training.csv")
df.head()




itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  
3                  0  Fungal infection  
4                  0  Fungal infection  

[5 rows x 133 columns]

In [28]:
df.shape

(4920, 133)

In [29]:
len(df['prognosis'].unique())

41








# **TRAIN TEST SPLIT**

In [30]:

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
X=df.drop("prognosis",axis=1)
y=df['prognosis']

In [31]:
X

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           1          1                     1                    0   
1           0          1                     1                    0   
2           1          0                     1                    0   
3           1          1                     0                    0   
4           1          1                     1                    0   
...       ...        ...                   ...                  ...   
4915        0          0                     0                    0   
4916        0          1                     0                    0   
4917        0          0                     0                    0   
4918        0          1                     0                    0   
4919        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       0           0             0        0                 0   
1             0       0           0             0        0                 0   
2             0       0           0             0        0                 0   
3             0       0           0             0        0                 0   
4             0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
4915          0       0           0             0        0                 0   
4916          0       0           0             0        0                 0   
4917          0       0           0             0        0                 0   
4918          0       0           1             0        0                 0   
4919          0       0           0             0        0                 0   

      ...  pus_filled_pimples  blackheads  scurring  skin_peeling  \
0     ...                   0           0         0             0   
1     ...                   0           0         0             0   
2     ...                   0           0         0             0   
3     ...                   0           0         0             0   
4     ...                   0           0         0             0   
...   ...                 ...         ...       ...           ...   
4915  ...                   0           0         0             0   
4916  ...                   1           1         1             0   
4917  ...                   0           0         0             0   
4918  ...                   0           0         0             1   
4919  ...                   0           0         0             0   

      silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
0                       0                     0                   0        0   
1                       0                     0                   0        0   
2                       0                     0                   0        0   
3                       0                     0                   0        0   
4                       0                     0                   0        0   
...                   ...                   ...                 ...      ...   
4915                    0                     0                   0        0   
4916                    0                     0                   0        0   
4917                    0                     0                   0        0   
4918                    1                     1                   1        0   
4919                    0                     0                   0        1   

      red_sore_around_nose  yellow_crust_ooze  
0                        0                  0  
1                        0                  0  
2                        0                  0  
3                        0                  0  
4                        0                  0  
...                    ...                ...  
4915                     0                  0  
4916              

In [32]:
y

0                              Fungal infection
1                              Fungal infection
2                              Fungal infection
3                              Fungal infection
4                              Fungal infection
                         ...                   
4915    (vertigo) Paroymsal  Positional Vertigo
4916                                       Acne
4917                    Urinary tract infection
4918                                  Psoriasis
4919                                   Impetigo
Name: prognosis, Length: 4920, dtype: object

In [33]:
le=LabelEncoder()
le.fit(y)
Y=le.transform(y)
Y

array([15, 15, 15, ..., 38, 35, 27])

In [34]:
X_train,X_test,y_train,y_test = train_test_split(X,Y, test_size=0.3, random_state=20)

# **Training Top Models**

In [35]:


from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import accuracy_score,confusion_matrix

models= {
    "SVC":SVC(kernel='linear'),
    "RandomForest":RandomForestClassifier(n_estimators=100,random_state=42),
   "GradientBoosting":GradientBoostingClassifier(n_estimators=100,random_state=42),
    "KNeighbors":KNeighborsClassifier(n_neighbors=5),
  "MultinomialNB":MultinomialNB()
}
for model_name,model in models.items():
  # TRAINING
  model.fit(X_train,y_train)
  # TESTING
  y_pred=model.predict(X_test)
  # ACCURACY
  accuracy=accuracy_score(y_test,y_pred)
  # Confusion matrix
  cm=confusion_matrix(y_test,y_pred)

  print(f"{model_name} has accuracy of {accuracy}")
  print(f"{model_name} Confsion matrix")
  # print(np.array2string(cm,separator=', '))
  print(cm)

SVC has accuracy of 1.0
SVC Confsion matrix
[[40  0  0 ...  0  0  0]
 [ 0 43  0 ...  0  0  0]
 [ 0  0 28 ...  0  0  0]
 ...
 [ 0  0  0 ... 34  0  0]
 [ 0  0  0 ...  0 41  0]
 [ 0  0  0 ...  0  0 31]]
RandomForest has accuracy of 1.0
RandomForest Confsion matrix
[[40  0  0 ...  0  0  0]
 [ 0 43  0 ...  0  0  0]
 [ 0  0 28 ...  0  0  0]
 ...
 [ 0  0  0 ... 34  0  0]
 [ 0  0  0 ...  0 41  0]
 [ 0  0  0 ...  0  0 31]]
GradientBoosting has accuracy of 1.0
GradientBoosting Confsion matrix
[[40  0  0 ...  0  0  0]
 [ 0 43  0 ...  0  0  0]
 [ 0  0 28 ...  0  0  0]
 ...
 [ 0  0  0 ... 34  0  0]
 [ 0  0  0 ...  0 41  0]
 [ 0  0  0 ...  0  0 31]]
KNeighbors has accuracy of 1.0
KNeighbors Confsion matrix
[[40  0  0 ...  0  0  0]
 [ 0 43  0 ...  0  0  0]
 [ 0  0 28 ...  0  0  0]
 ...
 [ 0  0  0 ... 34  0  0]
 [ 0  0  0 ...  0 41  0]
 [ 0  0  0 ...  0  0 31]]
MultinomialNB has accuracy of 1.0
MultinomialNB Confsion matrix
[[40  0  0 ...  0  0  0]
 [ 0 43  0 ...  0  0  0]
 [ 0  0 28 ...  0  0  0]
 ..

In [36]:

import pickle
import os

svc = SVC(kernel='linear')
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)
acc=accuracy_score(y_test,y_pred)

models_dir = 'models'
os.makedirs(models_dir, exist_ok=True)

# Save the model in the 'models' folder
model_path = os.path.join(models_dir, 'svc_modeLl.pkl')
with open(model_path, 'wb') as file:
    pickle.dump(svc, file)


In [37]:
# loading th model

with open(model_path, 'rb') as file:
    svc = pickle.load(file)

svc.predict(X_test.iloc[0].values.reshape(1,-1))


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([40])

In [38]:
symptoms=pd.read_csv('/content/symtoms_df.csv')
precautions=pd.read_csv('/content/precautions_df.csv')
workout=pd.read_csv('/content/workout_df.csv')
description=pd.read_csv('/content/description.csv')
medications=pd.read_csv('/content/medications.csv')
diets=pd.read_csv('/content/diets.csv')

In [39]:

symptoms_dict = {col: idx for idx, col in enumerate(X)}


In [40]:
disease_dict = {disease: label for disease, label in zip(y, Y)}

In [41]:
def helper(dis):
    desc = description[description['Disease'] == dis]['Description']
    desc = " ".join([w for w in desc])

    pre = precautions[precautions['Disease'] == dis][['Precaution_1', 'Precaution_2', 'Precaution_3', 'Precaution_4']]
    pre = [col for col in pre.values]

    med = medications[medications['Disease'] == dis]['Medication']
    med = [med for med in med.values]

    die = diets[diets['Disease'] == dis]['Diet']
    die = [die for die in die.values]

    wrkout = workout[workout['disease'] == dis]['workout']

    return desc, pre, med, die, wrkout


def predict_disease(patient_symptoms):
  input=np.zeros(len(symptoms_dict))

  for item in patient_symptoms:
    input[symptoms_dict[item]]=1

  input=input.reshape(1,-1)
  prediction=svc.predict(input)[0]
  disease_name=list(disease_dict.keys())[list(disease_dict.values()).index(prediction)]
  return disease_name


In [42]:
symptoms=input("Enter symptoms")
patient_symptoms = [symptom.strip() for symptom in symptoms.split(',')]
predicted_disease = predict_disease(patient_symptoms)
predicted_disease
desc, pre, med, die, wrkout=helper(predicted_disease)

print("=================Predicted disease============")
print(predicted_disease)
print("=================Description==================")
print(desc)
print("=================Precautions==================")
i = 1
for p_i in pre[0]:
    print(i, ": ", p_i)
    i += 1

print("=================Medications==================")
for m_i in med:
    print(i, ": ", m_i)
    i += 1

print("=================Workout==================")
for w_i in wrkout:
    print(i, ": ", w_i)
    i += 1

print("=================Diets==================")
for d_i in die:
    print(i, ": ", d_i)
    i += 1

Enter symptomsyellow_crust_ooze,red_sore_around_nose,small_dents_in_nails,inflammatory_nails,blister
=================Predicted disease============
Impetigo
=================Description==================
Impetigo is a highly contagious skin infection causing red sores that can break open.
=================Precautions==================
1 :  soak affected area in warm water
2 :  use antibiotics
3 :  remove scabs with wet compressed cloth
4 :  consult doctor
=================Medications==================
5 :  ['Topical antibiotics', 'Oral antibiotics', 'Antiseptics', 'Ointments', 'Warm compresses']
=================Workout==================
6 :  Maintain good hygiene
7 :  Stay hydrated
8 :  Consume nutrient-rich foods
9 :  Limit sugary foods and beverages
10 :  Include foods rich in vitamin C
11 :  Consult a healthcare professional
12 :  Follow medical recommendations
13 :  Avoid scratching
14 :  Take prescribed antibiotics
15 :  Practice wound care
=================Diets=================

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [43]:

desc

'Impetigo is a highly contagious skin infection causing red sores that can break open.'

In [44]:
for i in pre[0]:
  print(i)

soak affected area in warm water
use antibiotics
remove scabs with wet compressed cloth
consult doctor


In [45]:
import sklearn
import numpy as np
import pandas as pd
import pickle

print(sklearn.__version__)

print(np.__version__)


print(pd.__version__)

# print(pickle.__version__)

1.6.0
1.26.4
2.2.2
